# Python for AI — Class 14
### Pandas I: tables of data

**Pandas** is a Python library for **tables**, like Excel, but with code.
It is built on NumPy. Real data science work starts with Pandas.

## How we will learn today

Every topic has the same 4 steps:

| Step | What happens |
|------|--------------|
| **CONCEPT** | The teacher explains the idea. Short points. |
| **EXAMPLE** | The teacher types the code. **You type it too** and run it. |
| **QUICK CHECK** | You solve a small task alone. |
| **SOLUTION** | We check the answer together. The solutions are in a separate file. |

**Tip:** Run a cell with `Shift + Enter`.

# Hour 1: DataFrames and Reading Files

## CONCEPT: Series and DataFrame

- A **Series** is one column of data. It has a number (index) for each value.
- A **DataFrame** is a table: rows and columns. It is many Series together.
- We import Pandas as `pd`. Everyone uses this short name.

### EXAMPLE: Import Pandas and make a Series

In [2]:
import pandas as pd

In [3]:
prices = pd.Series([250, 480, 120, 990])
print(prices)

0    250
1    480
2    120
3    990
dtype: int64


The numbers on the left (0, 1, 2, 3) are the **index**. A Series works like a NumPy array, so maths works on every value:

In [4]:
print(prices * 2)
print(prices.max())

0     500
1     960
2     240
3    1980
dtype: int64
990


### ✏️ QUICK CHECK 1: Series

Make a Series `marks` from `[40, 55, 70, 90]`. Print `marks + 5` and `marks.mean()`.

Write your code in the cell below.

In [5]:
# Write your code here

### EXAMPLE: Make a DataFrame from a dictionary

*Each key is a column name. Each list is the values of that column.*

In [6]:
shop = pd.DataFrame({
    "item":  ["pen", "book", "bag"],
    "price": [20, 150, 900],
    "stock": [100, 40, 12],
})
print(shop)

   item  price  stock
0   pen     20    100
1  book    150     40
2   bag    900     12


In [7]:
print(shop.shape)     # (rows, columns)

(3, 3)


### ✏️ QUICK CHECK 2: DataFrame

Make a DataFrame `fruits` with a column `name` (`apple`, `mango`, `banana`) and a column `price` (`300`, `250`, `120`). Print it and its `.shape`.

Write your code in the cell below.

In [8]:
# Write your code here

## CONCEPT: Reading a CSV file

- A **CSV** file is a table saved as text. Values are separated by commas.
- `pd.read_csv("file.csv")` reads it into a DataFrame.
- Real data almost always comes from a file like this.
- Today our file is `students.csv`. The next cell makes it for you.

### EXAMPLE: Make the file and read it

*Run the first cell once. It writes `students.csv`. Then we read it.*

In [9]:
import pandas as pd

# Run this cell once. It makes the file students.csv
# (an empty place after a comma means the value is missing)
text = """name,age,city,maths,english,science
Ali,16,Lahore,80,72,91
Sara,15,Karachi,65,88,70
Hassan,17,Lahore,95,60,84
Ayesha,16,Islamabad,72,,78
Bilal,15,Karachi,55,64,
Fatima,16,Lahore,88,91,95
Usman,17,Islamabad,,58,62
Zainab,15,Karachi,92,85,89
Hamza,16,Lahore,45,50,48
Maryam,17,Islamabad,78,80,
"""

with open("students.csv", "w") as f:
    f.write(text)



In [10]:
df = pd.read_csv("students.csv")
print(df)

df.head()

     name  age       city  maths  english  science
0     Ali   16     Lahore   80.0     72.0     91.0
1    Sara   15    Karachi   65.0     88.0     70.0
2  Hassan   17     Lahore   95.0     60.0     84.0
3  Ayesha   16  Islamabad   72.0      NaN     78.0
4   Bilal   15    Karachi   55.0     64.0      NaN
5  Fatima   16     Lahore   88.0     91.0     95.0
6   Usman   17  Islamabad    NaN     58.0     62.0
7  Zainab   15    Karachi   92.0     85.0     89.0
8   Hamza   16     Lahore   45.0     50.0     48.0
9  Maryam   17  Islamabad   78.0     80.0      NaN


,name,age,city,maths,english,science
0,Ali,16,Lahore,80.0,72.0,91.0
1,Sara,15,Karachi,65.0,88.0,70.0
2,Hassan,17,Lahore,95.0,60.0,84.0
3,Ayesha,16,Islamabad,72.0,NaN,78.0
4,Bilal,15,Karachi,55.0,64.0,NaN


### ✏️ QUICK CHECK 3: Read a CSV

Read `students.csv` into a new variable `data`. Print only the first 3 rows with `.head(3)`.

Write your code in the cell below.

In [11]:
# Write your code here
df.describe()

,age,maths,english,science
count,10.000000,9.000000,9.000000,8.000000
mean,16.000000,74.444444,72.000000,77.125000
std,0.816497,16.949271,14.739403,16.163782
min,15.000000,45.000000,50.000000,48.000000
25%,15.250000,65.000000,60.000000,68.000000
50%,16.000000,78.000000,72.000000,81.000000
75%,16.750000,88.000000,85.000000,89.500000
max,17.000000,95.000000,91.000000,95.000000


## CONCEPT: Look at your data first

- `df.head(n)` shows the first `n` rows (default 5). `df.tail(n)` shows the last rows.
- `df.shape` = (rows, columns).
- `df.info()` = column names, types, and how many values are **not** missing.
- `df.describe()` = count, average, min, max and more for the number columns.
- Always do this first. Then you know what is in your data.

### EXAMPLE: Inspect the DataFrame

In [44]:
print(df.head())
df.head(20)

     name  age       city  maths  english  science
0     Ali   16     Lahore   80.0     72.0     91.0
1    Sara   15    Karachi   65.0     88.0     70.0
2  Hassan   17     Lahore   95.0     60.0     84.0
3  Ayesha   16  Islamabad   72.0      NaN     78.0
4   Bilal   15    Karachi   55.0     64.0      NaN


,name,age,city,maths,english,science
0,Ali,16,Lahore,80.0,72.0,91.0
1,Sara,15,Karachi,65.0,88.0,70.0
2,Hassan,17,Lahore,95.0,60.0,84.0
3,Ayesha,16,Islamabad,72.0,NaN,78.0
4,Bilal,15,Karachi,55.0,64.0,NaN
5,Fatima,16,Lahore,88.0,91.0,95.0
6,Usman,17,Islamabad,NaN,58.0,62.0
7,Zainab,15,Karachi,92.0,85.0,89.0
8,Hamza,16,Lahore,45.0,50.0,48.0
9,Maryam,17,Islamabad,78.0,80.0,NaN


In [13]:
print(df.shape)
print(df.columns)

(10, 6)
Index(['name', 'age', 'city', 'maths', 'english', 'science'], dtype='object')


In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   name     10 non-null     object 
 1   age      10 non-null     int64  
 2   city     10 non-null     object 
 3   maths    9 non-null      float64
 4   english  9 non-null      float64
 5   science  8 non-null      float64
dtypes: float64(3), int64(1), object(2)
memory usage: 612.0+ bytes


Look at the `Non-Null Count` column. Some columns have less than 10 values. These have **missing values**. We will fix them later today.

In [15]:
print(df.describe())

             age      maths    english    science
count  10.000000   9.000000   9.000000   8.000000
mean   16.000000  74.444444  72.000000  77.125000
std     0.816497  16.949271  14.739403  16.163782
min    15.000000  45.000000  50.000000  48.000000
25%    15.250000  65.000000  60.000000  68.000000
50%    16.000000  78.000000  72.000000  81.000000
75%    16.750000  88.000000  85.000000  89.500000
max    17.000000  95.000000  91.000000  95.000000


### ✏️ QUICK CHECK 4: Inspect

Using `df`, print how many rows it has, and then call `df.describe()`. What is the average Maths mark?

Write your code in the cell below.

In [16]:
# Write your code here

# Hour 2: Selecting, Filtering and Sorting

## CONCEPT: Select columns

- One column: `df["maths"]` gives a **Series**.
- Many columns: `df[["name", "maths"]]` (a list inside the brackets) gives a **DataFrame**.
- A column has maths functions too: `df["maths"].mean()`.

### EXAMPLE: Pick columns

In [45]:
print(df["name"])

0       Ali
1      Sara
2    Hassan
3    Ayesha
4     Bilal
5    Fatima
6     Usman
7    Zainab
8     Hamza
9    Maryam
Name: name, dtype: object


In [46]:
print(df[["name", "maths"]])     # two brackets: a list of columns

     name  maths
0     Ali   80.0
1    Sara   65.0
2  Hassan   95.0
3  Ayesha   72.0
4   Bilal   55.0
5  Fatima   88.0
6   Usman    NaN
7  Zainab   92.0
8   Hamza   45.0
9  Maryam   78.0


In [19]:
print(df["maths"].mean())        # average of the Maths column
print(df["maths"].max())

74.44444444444444
95.0


### ✏️ QUICK CHECK 5: Select columns

Print the columns `name` and `science`. Then print the highest Science mark.

Write your code in the cell below.

In [20]:
# Write your code here

## CONCEPT: Select rows: iloc and loc

- `df.iloc[row_number]` picks rows by **position** (0, 1, 2...).
- `df.loc[row, "column"]` picks by **label**: the row index and the column name.
- A slice works like a list: `df.iloc[0:3]` gives rows 0, 1, 2 (stop is not included).

### EXAMPLE: iloc and loc

In [55]:
df.info()
# print(df.iloc[1])            # the first row

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   name     10 non-null     object 
 1   age      10 non-null     int64  
 2   city     10 non-null     object 
 3   maths    9 non-null      float64
 4   english  9 non-null      float64
 5   science  8 non-null      float64
dtypes: float64(3), int64(1), object(2)
memory usage: 612.0+ bytes


In [51]:
print(df.iloc[0:3])          # first 3 rows

     name  age     city  maths  english  science
0     Ali   16   Lahore   80.0     72.0     91.0
1    Sara   15  Karachi   65.0     88.0     70.0
2  Hassan   17   Lahore   95.0     60.0     84.0


In [54]:
print(df.loc[0, ["age", "maths"]])     # row 1, column name
# print(df.loc[1, "maths"])

age        16
maths    80.0
Name: 0, dtype: object


### ✏️ QUICK CHECK 6: Select rows

Print the **last** row with `iloc[-1]`. Then print the `city` of row 3 using `loc`.

Write your code in the cell below.

In [24]:
# Write your code here

## CONCEPT: Filter rows with a condition

- It is the same idea as a NumPy filter.
- A comparison gives True/False for every row. Put it inside `df[ ]`.
- For more than one condition, use `&` (and), `|` (or). Put **brackets** around each one.
- Do **not** use `and` / `or` here. It gives an error.

### EXAMPLE: Filter students

In [25]:
print(df["maths"] > 80)           # True/False for each student

0    False
1    False
2     True
3    False
4    False
5     True
6    False
7     True
8    False
9    False
Name: maths, dtype: bool


In [26]:
print(df[df["maths"] > 80])       # only the rows that are True

     name  age     city  maths  english  science
2  Hassan   17   Lahore   95.0     60.0     84.0
5  Fatima   16   Lahore   88.0     91.0     95.0
7  Zainab   15  Karachi   92.0     85.0     89.0


In [27]:
print(df[df["city"] == "Lahore"])         # == means "is equal to"

     name  age    city  maths  english  science
0     Ali   16  Lahore   80.0     72.0     91.0
2  Hassan   17  Lahore   95.0     60.0     84.0
5  Fatima   16  Lahore   88.0     91.0     95.0
8   Hamza   16  Lahore   45.0     50.0     48.0


In [28]:
print(df[(df["city"] == "Lahore") & (df["maths"] >= 80)])    # two conditions

     name  age    city  maths  english  science
0     Ali   16  Lahore   80.0     72.0     91.0
2  Hassan   17  Lahore   95.0     60.0     84.0
5  Fatima   16  Lahore   88.0     91.0     95.0


### ✏️ QUICK CHECK 7: Filter

Print the students whose `english` is **more than 70**. Then print the students from `Karachi` whose `science` is **less than 90**.

Write your code in the cell below.

In [29]:
# Write your code here

## CONCEPT: Sort rows

- `df.sort_values("maths")` sorts from small to big.
- `ascending=False` sorts from big to small.
- Sort does not change `df`. It gives you a new sorted table.
- `.head(3)` after sorting gives the top 3.

### EXAMPLE: Sort the students

In [56]:
print(df.sort_values("maths"))

     name  age       city  maths  english  science
8   Hamza   16     Lahore   45.0     50.0     48.0
4   Bilal   15    Karachi   55.0     64.0      NaN
1    Sara   15    Karachi   65.0     88.0     70.0
3  Ayesha   16  Islamabad   72.0      NaN     78.0
9  Maryam   17  Islamabad   78.0     80.0      NaN
0     Ali   16     Lahore   80.0     72.0     91.0
5  Fatima   16     Lahore   88.0     91.0     95.0
7  Zainab   15    Karachi   92.0     85.0     89.0
2  Hassan   17     Lahore   95.0     60.0     84.0
6   Usman   17  Islamabad    NaN     58.0     62.0


In [57]:
print(df.sort_values("maths", ascending=True).head(3))     # top 3 in Maths

    name  age     city  maths  english  science
8  Hamza   16   Lahore   45.0     50.0     48.0
4  Bilal   15  Karachi   55.0     64.0      NaN
1   Sara   15  Karachi   65.0     88.0     70.0


In [32]:
print(df.sort_values(["city", "name"]))      # sort by city, then by name

     name  age       city  maths  english  science
3  Ayesha   16  Islamabad   72.0      NaN     78.0
9  Maryam   17  Islamabad   78.0     80.0      NaN
6   Usman   17  Islamabad    NaN     58.0     62.0
4   Bilal   15    Karachi   55.0     64.0      NaN
1    Sara   15    Karachi   65.0     88.0     70.0
7  Zainab   15    Karachi   92.0     85.0     89.0
0     Ali   16     Lahore   80.0     72.0     91.0
5  Fatima   16     Lahore   88.0     91.0     95.0
8   Hamza   16     Lahore   45.0     50.0     48.0
2  Hassan   17     Lahore   95.0     60.0     84.0


### ✏️ QUICK CHECK 8: Sort

Print the **top 3 students in English**. Show only the columns `name` and `english`.

Write your code in the cell below.

In [33]:
# Write your code here

# Hour 3: Missing Values and Practice

## CONCEPT: Missing values

- Real data has empty places. Pandas shows them as `NaN` (not a number).
- `df.isna()` gives True where a value is missing.
- `df.isna().sum()` counts the missing values in each column.
- Functions like `.mean()` skip `NaN` by themselves.

### EXAMPLE: Find the missing values

In [34]:
print(df)

     name  age       city  maths  english  science
0     Ali   16     Lahore   80.0     72.0     91.0
1    Sara   15    Karachi   65.0     88.0     70.0
2  Hassan   17     Lahore   95.0     60.0     84.0
3  Ayesha   16  Islamabad   72.0      NaN     78.0
4   Bilal   15    Karachi   55.0     64.0      NaN
5  Fatima   16     Lahore   88.0     91.0     95.0
6   Usman   17  Islamabad    NaN     58.0     62.0
7  Zainab   15    Karachi   92.0     85.0     89.0
8   Hamza   16     Lahore   45.0     50.0     48.0
9  Maryam   17  Islamabad   78.0     80.0      NaN


In [61]:
print(df.isna().sum())   

df.shape   # missing values in each column

name       0
age        0
city       0
maths      1
english    1
science    2
dtype: int64


(10, 6)

### ✏️ QUICK CHECK 9: Find missing values

Find how many values are missing in `science`. Then print the rows where `maths` is missing.

Write your code in the cell below.

In [36]:
# Write your code here

## CONCEPT: Fix missing values: dropna and fillna

- `df.dropna()` removes every row that has a missing value.
- `df.fillna(value)` puts a value in the empty places.
- A common choice: fill with the **average** of the column.
- Both give a **new** table. Save it in a new variable.

### EXAMPLE: Drop or fill

In [64]:
clean = df.dropna()
print(clean.shape)       # fewer rows now
print(clean)

df.dropna().head(20)

(6, 6)
     name  age     city  maths  english  science
0     Ali   16   Lahore   80.0     72.0     91.0
1    Sara   15  Karachi   65.0     88.0     70.0
2  Hassan   17   Lahore   95.0     60.0     84.0
5  Fatima   16   Lahore   88.0     91.0     95.0
7  Zainab   15  Karachi   92.0     85.0     89.0
8   Hamza   16   Lahore   45.0     50.0     48.0


,name,age,city,maths,english,science
0,Ali,16,Lahore,80.0,72.0,91.0
1,Sara,15,Karachi,65.0,88.0,70.0
2,Hassan,17,Lahore,95.0,60.0,84.0
5,Fatima,16,Lahore,88.0,91.0,95.0
7,Zainab,15,Karachi,92.0,85.0,89.0
8,Hamza,16,Lahore,45.0,50.0,48.0


`dropna` threw away 4 students. That is a lot of data. Filling is often better.

In [65]:
avg = df["maths"].mean()
print("Maths average:", avg)

filled = df.copy()                              # a copy, so df stays the same
filled["maths"] = filled["maths"].fillna(avg)
print(filled[["name", "maths"]])

Maths average: 74.44444444444444
     name      maths
0     Ali  80.000000
1    Sara  65.000000
2  Hassan  95.000000
3  Ayesha  72.000000
4   Bilal  55.000000
5  Fatima  88.000000
6   Usman  74.444444
7  Zainab  92.000000
8   Hamza  45.000000
9  Maryam  78.000000


### ✏️ QUICK CHECK 10: Fill missing values

Make a copy of `df` called `fixed`. Fill the missing `science` marks with `0`. Print `fixed[["name", "science"]]`.

Write your code in the cell below.

In [39]:
# Write your code here

# Practice

### ✏️ QUICK CHECK 11: Practice

Find the students from `Lahore`. Print only their `name` and `maths`, sorted from the highest Maths mark.

Write your code in the cell below.

In [40]:
# Write your code here

### ✏️ QUICK CHECK 12: Practice (Harder)

1) Fill the missing marks in `maths`, `english` and `science` with each column's average. (Hint: do it one column at a time.)
2) Print the students whose `english` is more than 70 and `maths` is more than 70, sorted by `name`.

Write your code in the cell below.

In [41]:
# Write your code here

# Home Practice: Interview-Style Questions

1. What is the difference between a Series and a DataFrame?
2. What does `df.info()` tell you? Why do we call it first?
3. What is the difference between `iloc` and `loc`?
4. Why do we use `&` and not `and` when we filter a DataFrame?
5. What does `NaN` mean? Name two ways to deal with it.
6. Does `df.sort_values("maths")` change `df`? How do you keep the sorted result?

**Extra:** Read `students.csv`. Print the name of the student with the highest Science mark. (Hint: sort, then use `.iloc[0]`.)

# Key Takeaways

- A **DataFrame** is a table. A **Series** is one column.
- `pd.read_csv()` reads a file. Then use `head`, `shape`, `info` and `describe` to look at it.
- `df["col"]` = one column. `df[["a", "b"]]` = many columns.
- `iloc` = by position. `loc` = by label.
- Filter with `df[condition]`. Use `&`, `|` with brackets.
- `sort_values` sorts. `ascending=False` = big to small.
- `isna().sum()` counts missing values. `dropna()` removes them. `fillna()` fills them.

**Next class:** Pandas II: groupby, merge and new columns.